In [62]:
import numpy as np
import scipy as sc

Metoda potęgowa

In [52]:
def power_method(A):
    n, m = A.shape
    x = np.ones((n, 1))
    lambda_o = 0

    for i in range(100):
        x_p = A @ x
        lambda_n = np.linalg.norm(x_p, np.inf)

        x_p /= lambda_n

        if abs(lambda_n - lambda_o) < 1e-5:
            return lambda_n, x_p, i

        lambda_o = lambda_n
        x = x_p
            
        x = x_p
    
    
    
    return lambda_o, x, 100 

In [37]:
A = np.random.rand(100, 100)
A = (A + A.T) / 2


In [53]:
lambda_o, x, i = power_method(A)

In [54]:
print(lambda_o)
print(x)

50.196759018671806
[[0.88927523]
 [0.91065242]
 [0.91168117]
 [0.94951734]
 [0.89034628]
 [0.90855341]
 [0.90532727]
 [0.89948734]
 [0.91965352]
 [0.86221247]
 [0.92503359]
 [0.8955236 ]
 [0.915722  ]
 [0.91632998]
 [0.89178142]
 [0.91370604]
 [0.86608663]
 [0.90709526]
 [0.90696497]
 [0.88968269]
 [0.95683583]
 [0.86246804]
 [0.93880644]
 [0.90401837]
 [0.84330961]
 [0.91714725]
 [0.85587781]
 [0.8316307 ]
 [0.93743102]
 [0.92424875]
 [0.91962179]
 [0.86428089]
 [0.8890898 ]
 [0.9099328 ]
 [0.93216376]
 [0.91399134]
 [0.80857684]
 [1.        ]
 [0.90754714]
 [0.91838742]
 [0.94498031]
 [0.90165823]
 [0.88373528]
 [0.95478618]
 [0.90244474]
 [0.87595158]
 [0.87993454]
 [0.87806059]
 [0.91434867]
 [0.90604871]
 [0.88757043]
 [0.94982187]
 [0.87525966]
 [0.86023751]
 [0.91664499]
 [0.83186939]
 [0.89983257]
 [0.90196057]
 [0.8950543 ]
 [0.89296354]
 [0.87814507]
 [0.8818946 ]
 [0.87056532]
 [0.9421897 ]
 [0.89274862]
 [0.93825012]
 [0.93617478]
 [0.86347046]
 [0.91280019]
 [0.93936612]
 

In [61]:
w, v = np.linalg.eig(A)
max_index = np.argmax(w)
max_val = w[max_index]
max_vec = v[:, max_index]

print(abs(max_val) - lambda_o)

max_vec_normalized = max_vec / np.linalg.norm(max_vec, np.inf)

print(
    np.linalg.norm(np.abs(max_vec_normalized) - np.abs(x.flatten()), np.inf)
)


-2.2945072117863674e-06
6.581839850916538e-09


Odwrotna macierz potęgowa

In [87]:
def reversed_power(A):
    n = A.shape[0]
    #lu, piv = sc.linalg.lu_factor(B)

    x = np.ones(n)

    for _ in range(20):
        sigma = np.random.randint(0, 20)
        B = A - sigma * np.eye(n)
        B = np.linalg.inv(B)

        u, piv = sc.linalg.lu_factor(B)
        lambda_o = 0
        lambda_n = 0

        for j in range(100):
            x_p = sc.linalg.lu_solve((u, piv), x)
            lambda_n = np.linalg.norm(x_p, np.inf)

            x_p /= lambda_n

            if abs(lambda_n - lambda_o) < 1e-5:
                lambda_o = lambda_n
                x = x_p
                break

            lambda_o = lambda_n
            x = x_p

        print(lambda_o)

            

In [88]:
reversed_power(A)

31.196671391968653
47.19675711083397
42.19675674160706
41.19675672575323
39.19675672435667
32.19675672421443
37.196756724180034
46.196756724164146
33.19675672416511
33.19675672416476
34.19675672416461
43.19675672416458
40.19675672416454
37.19675672416443
36.19675672416446
36.19675672416464
31.19675672416459
31.19675672416467
46.196756724162945
37.196756724164985


In [97]:
def ray(A):
    n, m = A.shape
    x = np.ones((n, 1))
    lambda_o = 0

    sigma = (x.T @ A @ x) / (x.T @ x)

    B = A - sigma * np.eye(n)

    lambda_o = 0
    sigma = 0

    for j in range(100):
        B = A - sigma * np.eye(n)

        x_p = np.linalg.solve(B, x)
        lambda_n = np.linalg.norm(x_p, np.inf)

        x_p /= lambda_n

        if abs(lambda_n - lambda_o) < 1e-5:
            lambda_o = lambda_n
            x = x_p
            break

        lambda_o = lambda_n
        x = x_p

        sigma = (x.T @ A @ x) / (x.T @ x)
        B = A - sigma * np.eye(n)

    return sigma, x

In [98]:
ray(A)

(array([[0.16485321]]),
 array([[-0.33998677],
        [-0.21345923],
        [ 0.32195297],
        [ 0.04095925],
        [-0.61647088],
        [-0.08651967],
        [-0.15047614],
        [-0.81260197],
        [-0.36308295],
        [-0.32190233],
        [ 0.40724804],
        [ 0.19107931],
        [ 0.6147781 ],
        [ 0.01495784],
        [ 0.93486745],
        [ 0.51670045],
        [-0.4401456 ],
        [ 0.27328774],
        [ 0.51422018],
        [ 0.30704393],
        [ 0.02152661],
        [ 0.29004713],
        [-0.27550223],
        [ 0.07374067],
        [ 0.57625549],
        [-0.58616483],
        [ 0.0105798 ],
        [-0.28120717],
        [-0.27376805],
        [-0.48727017],
        [-0.5105937 ],
        [-0.23734786],
        [-0.4363349 ],
        [-0.22024605],
        [ 0.3916198 ],
        [-0.51401578],
        [-0.45969392],
        [ 0.38743087],
        [-0.14189461],
        [-0.81552169],
        [-0.07478936],
        [ 0.00630037],
        [-